### ISSUE TITLE
The value of the `NO_DISK_LOGGER` environment variable is inverted

### ISSUE THREAD

**Issue by vitoyucepi** [slskd/slskd#1115]
## Summary

There is a mismatch between the `NO_DISK_LOGGER` environment variable and its logical value.

## Actual behavior

Currently, when `NO_DISK_LOGGER=true`, the disk logging feature remains enabled.
When `NO_DISK_LOGGER=false`, the disk logging feature is disabled.

## Expected behavior

When `NO_DISK_LOGGER=true`, the disk logging feature should be disabled.
If `NO_DISK_LOGGER=false`, the disk logging feature should be enabled.

## Additionally

Maybe `NO_DISK_LOGGER` should be replaced with `LOG_TO_DISK` or `ENABLE_DISK_LOGGER`.

## Versions

- slskd: *0.20.1.0*.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I made a mistake when I added this option; the backing value for this should have been false by default, the application logic that looks at it should have been inverted, and the name of the backing property should have been something like `NoDisk`.

I can't fix this without a breaking change, and because I think disk logging is probably of low value for most people, I'm disabling it by default to fix this behavior.
