### ISSUE TITLE
High load every 10 minutes when `SLSKD_SHARE_CACHE_RETENTION` is unset

### ISSUE THREAD

**Issue by vitoyucepi** [slskd/slskd#1161]
## Summary

I may be wrong, but it seems that when share cache retention is not set, slskd tries to do something every 10 minutes.
I'm using the following settings:
```env
SLSKD_SHARE_CACHE_STORAGE_MODE="disk"
SLSKD_SHARE_CACHE_WORKERS=1
```

## Actual behavior

![Screenshot of Prometheus showing peaks every 10 minutes reported by slskd and node exporters.](https://github.com/slskd/slskd/assets/35035879/3cb60447-821f-4063-a537-8548433e3cb6)

## Expected behavior

1. There should be log records for running background tasks.
1. If I'm right, cache retention should be set to a more reasonable amount of time.
1. Update the documentation regarding this behavior.

## Versions

- slskd: *0.21.1.0*.

## Additionally

Probably related to #965.

**Comment by jpdillingham** [comment]
The only capacity for running things on a regular interval is provided by the `Clock` class which offers 1 minute, 5 minute, 30 minute and 60 minute intervals.

The only thing I can think of that might cause this (and I'm not sure how since it's on a 5 minute interval) is the "pruning" of upload and download records; a database query that fetches all of the records older than the configured retention period that have not been removed from the UI, and then iterates over them and marks them removed.  There's a good possibility that this would introduce a fairly heavy CPU load for high traffic users, as I don't believe there are any indexes on those tables.

Can you share your retention settings?  Specifically the ones described [here](https://github.com/slskd/slskd/blob/master/docs/config.md#data-retention).

Regarding the share cache, there's a "task" that runs every 60 minutes and invokes the `MaybeRescanShares` method.  If there's no configured retention (which defaults to null) then shares will never be rescanned while the application is running unless the user invokes it.  There's some additional logic that will determine whether a scan is required as the application is starting, though.

**Comment by vitoyucepi** [comment]
> Can you share your retention settings? Specifically the ones described here.

```yaml
retention:
  transfers:
    upload:
      succeeded: 2880 # 2 days
      errored: 720 # 12 hours
      cancelled: 720 # 12 hours
    download:
      succeeded: 10080 # 1 week
      errored: 20160 # 2 weeks
      cancelled: 1440 # 1 day
```

**Comment by vitoyucepi** [comment]
I would like to close this issue because I have done something (most likely a rescan of the directory) and the behavior has gone away.

**Comment by jpdillingham** [comment]
Thanks for following up! If it comes back please reopen.
