### ISSUE TITLE
Looking for an option to put a lock behind certain files/folders

### ISSUE THREAD

**Issue by StayBlue** [slskd/slskd#1185]
If an option like this already exists, I haven't been able to find it yet. I'm looking for an option/setting to put a lock behind a certain file/folder, as in put a password or something similar such that only certain people can access it. I think this is a thing as I've seen people put it on certain files before, but I haven't had a need to do so myself until now. Is there any option to do this currently?

**Comment by jpdillingham** [comment]
Locked files aren't supported due to ideological reasons.  You can read more in the discussion #647.  My goal is to continue to add features to slskd that negate the desire to lock files, specifically the desire to advertise files in search and browse results that aren't available to download without additional steps.  If you have a use case that hasn't been discussed please feel free to share it in the linked discussion.

The ability to add userlist specific directories is being discussed in #937, and is something I'll eventually get to.

**Comment by StayBlue** [comment]
I am glad I opened an issue for this so that other people can discover the discussion more easily. Thanks for the quick reply!
