### ISSUE TITLE
Compatibility with prometheus 3.0

### ISSUE THREAD

**Issue by vitoyucepi** [slskd/slskd#1243]
## Summary

The `/metrics` endpoint should provide a `Content-Type` HTTP header known to Prometheus.

## Details

Since the release of Prometheus 3.0, the exporter is required to provide a supported `Content-Type` HTTP header, as stated in the migration manual available at https://prometheus.io/docs/prometheus/latest/migration/#scrape-protocols.
The `prometheus-net` library supports the required header, but slskd doesn't send it for some reason. https://github.com/prometheus-net/prometheus-net/blob/60e9106a83ff1274fec0022c37366f04822b1d1b/Prometheus/PrometheusConstants.cs

## Actual behavior

The `/metrics` endpoint doesn't return the `Content-Type` HTTP header.

## Expected behavior

The `/metrics` endpoint serves the result with the correct `Content-Type` HTTP header, compatible with Prometheus 3.0.

## Versions

- slskd: *0.21.4*

**Comment by jpdillingham** [comment]
Thanks for reporting this.  Reviewing the code; I somewhat hacked this together to add basic authentication to this endpoint in #616.  I didn't do my homework on the default behavior of the existing endpoint and neglected to set a content type.

Reviewing the code you linked it seems there's more to it than just `text/plain`, so I'll have to dig further.

**Comment by jpdillingham** [comment]
Making a note for myself so I don't spend another 20 minutes re-learning this;

The only guidance from the prometheus-net maintainers was given in 2018, where they suggested to use `app.Map("/metrics")`, apply auth middleware, and then `app.UseMetricServer()`.  _This doesn't work in an application that is using `app.UseEndpoints()`_.  I don't know why because the ASP.NET team keeps dicking around with this stuff and I can't keep up.

That being said, the linked library is doing exactly what I am, just with more steps plus the content-type header.  I'll push a PR to fix this momentarily.

**Comment by jpdillingham** [comment]
Should be out in the canary about 20 minutes from now.  Let me know if it works!

**Comment by vitoyucepi** [comment]
The `slskd/slskd:canary@sha256:a34176a107a34c6d5165788d26771a6d0d6fe8e7d6483c50b525094396a1a000` works fine with `prom/prometheus:v3.0.0@sha256:3b9b2a15d376334da8c286d995777d3b9315aa666d2311170ada6059a517b74f`.

**Comment by jpdillingham** [comment]
Thanks for confirming! I'll get this released next week while I've got some time off.
