### ISSUE TITLE
Add ability to limit upload / download speed and slots

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#127]
Another nice to have feature:
It would be nice to be able to limit speeds e.g. during working hours, as well as limit upload slots as in SoulSeekQT.

**Comment by jpdillingham** [comment]
Thanks for raising this.

These features are a few of the ones I consider necessary before the software can reach a 1.0.0 release.  The broader set of features includes a round-robin style queue, speed governance and limits on concurrent downloads.  These things are all related, and probably won't look a lot like the existing Soulseek implementation when finished.

**Comment by jpdillingham** [comment]
I'm adding the `help wanted` label because this is a fairly large chunk of work.  I'd be delighted to talk someone through the approach and provide support as needed!

Speed governance should be fairly straightforward, as both `UploadAsync()` and `DownloadAsync()` methods of the Soulseek.NET lib accept options which include a delegate specifically for this, someone just needs to figure out how much of a wait (if any) the governor should perform and synchronize that across active transfers.

The limits and queue are pretty closely related, and whoever picks this up would be starting from basically scratch on both fronts.

**Comment by jpdillingham** [comment]
Thinking through this a bit, I think limiting slots is quite a bit easier than upload speeds.  The approach would be to create a shared [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket), which doesn't work a lot differently than how uploads are constrained to a single active upload in Soulseek.NET.

This won't be as simple as starting uploads asynchronously and letting .NET handle them; a queue will need to be introduced so that uploads aren't started unless they can begin immediately.

There's potentially a way to do this by making Soulseek.NET aware of a global queueing semaphore, which would simplify this quite a bit.  There would be no good way to  persist the state of the queue through an application restart, but Soulseek Qt/NS doesn't do this today (downloaders must re-enqueue manually), so maybe there's no issue.

**Comment by kromsam** [comment]
> Another nice to have feature: It would be nice to be able to limit speeds e.g. during working hours, as well as limit upload slots as in SoulSeekQT.

I think this would be a great feature as well. Maybe in the mean time we can find a way to throttle the bandwidth of the docker container as a whole. I am sure there must be ways to do that.

**Comment by jpdillingham** [comment]
I'm going to be moving forward with this by implementing a global speed limit and upload slot cap.  One of my primary goals is to have a comprehensive class-based system for this, but it needs a ton of design still and will take a lot to implement, so something in the interim is practical.

I'm still planning the comprehensive approach for version 1.0, it'll just have to wait.

**Comment by jpdillingham** [comment]
This turned into a massive detour in Soulseek.NET: https://github.com/jpdillingham/Soulseek.NET/issues/633

The good news is that it will now be fairly trivial to implement a comprehensive queue.  The bad news is that this work didn't address the speed limits and I don't have a plan (yet) for implementation.

Soulseek.NET 4.0.0 will be released in a few days, and I'll update slskd shortly after with a basic upload cap, round-robin queue and something that prioritizes privileged users on the network.

In the meantime, anyone needing a solution for rate limiting should take a look at the suggestions shared by @kromsam.
