### ISSUE TITLE
Lowercase transfer requests resulting in a 'File not shared' message

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#261]
Some client (this is a known thing, I just forget which) is transmitting requested filenames in all lower case.  I had thought I was handling these properly, but am not.

All filenames will need to be lowercased during the scan and stored in all lowercase.  All file requests will need to be lowercased prior to searching the share for a match.

**Comment by mathiascode** [comment]
This is a bug in Soulseek NS, specifically in the "Download Containing Folder" option in search results. The bug doesn't occur when downloading a folder from the file browse view, however.

> All filenames will need to be lowercased during the scan and stored in all lowercase.

I would not go the same route as Soulseek NS here. It ruins file/folder names, and Nir has admitted it was a bad decision in the past: http://www.soulseekqt.net/news/comment/1334#comment-1334

Since many other parts of Soulseek NS are broken nowadays (most file attributes, user info pictures, special characters in chats etc), I think users either have to live with these issues or start upgrading to a client that hasn't been abandoned for 12 years now.

**Comment by jpdillingham** [comment]
Works for me, I wasn't looking forward to doing this.  Thanks!
