### ISSUE TITLE
Downloads often fail on 0.14, unhandled exceptions and write buffer overflow

### ISSUE THREAD

**Issue by Moondownr** [slskd/slskd#318]
Since the upgrade to 0.14, about half the time I try to enqueque a folder, it fails. When I retry, it usually connects, but the individual downloads sometimes error out (usually about 1 in 8-10). Browsing the logs. I'm getting a few new error messages (at least ones I never noticed with 0.13), namely, quite a lot of those:

> Connection id ""0HME2BTOBK8UC"", Request id ""0HME2BTOBK8UC:00000072"": An unhandled exception was thrown by the application.

Some of those:

> Child connection to Leobiess (82.170.139.231:53193) disconnected: Read error: Remote connection closed

And one or two of these:

> Child connection to A_100 (90.131.45.225:17985) disconnected: The write buffer is full

I'm not sure, how many different issues are in here, sorry.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I was hoping that #300 would fix it, but I'm still getting it from time to time too.  It seems like the problem is worse when downloading from someone using Soulseek NS, so there may be a nuance in connectivity that I don't yet understand.  The root problem is that the initial connection times out, but I don't know why, especially because subsequent attempts succeed.

Regarding the child connection errors, those are normal and expected.  The write buffer disconnect was introduced in #278 to stop these connections from blowing up memory before the application can figure out that the connection is bad.  Any log message relating to parent or child connections is specific to the distributed network and won't impact the application in a way that you'd notice.

**Comment by jpdillingham** [comment]
I've added detailed logging to the endpoint that enqueues downloads.  With debug level logging enabled, you should see something like:

```
[slskd.Transfers.API.TransfersController] [] [20:56:54 INF] Downloading 13 files from user <redacted>
[slskd.Transfers.API.TransfersController] [] [20:56:54 DBG] Priming connection for user <redacted>
[slskd.Transfers.API.TransfersController] [] [20:56:54 DBG] Connection for user '<redacted>' primed
[slskd.Transfers.API.TransfersController] [] [20:56:55 DBG] Attempting to enqueue <filename> from user <redacted>
[slskd.Transfers.API.TransfersController] [] [20:56:55 DBG] Successfully enqueued <filename> from user <redacted>
...
[slskd.Transfers.API.TransfersController] [] [20:56:55 INF] Successfully enqueued 13 files from user <redacted>
```

This change should be out in about 20 minutes with 0.14.1; if you could capture and share logs when you encounter the issue it would be a big help.

**Comment by jpdillingham** [comment]
I'm pretty sure this issue was resolved in this commit in Soulseek.NET: https://github.com/jpdillingham/Soulseek.NET/commit/648ca4b1b71b8f4429d894d92362b83beb0fad57

I haven't seen this problem since I made this change, so I'll close this for now, but feel free to reopen it if you're still having issues.
