### ISSUE TITLE
Downloading file with special character fails

### ISSUE THREAD

**Issue by mtoniott** [slskd/slskd#329]
Speaking french, songs with special characters (é, è, ê ) are fairly common. When downloading albums (full folders) using slskd, tracks with a special character in their name fail silently.

If I retry later, it will work, but it is annoying that it fails silently the first time.

**Comment by jpdillingham** [comment]
I'll check to see if there's been a regression with encoding.  Files with accented characters can't be downloaded from users using Soulseek NS due to the inability of that application to handle UTF-8 encoded text.  These transfers will generally always be rejected by the remote client, and won't succeed on retries.

Downloads failing initially and then succeeding later is an observed behavior that I've never been able to replicate or fully resolve, that might be what you are seeing.

Can you reproduce this issue reliably? If so it would be helpful if you could enable debugging and send me some logs.

**Comment by jpdillingham** [comment]
I just released 0.14.2, which uses Soulseek.NET 4.1.0 and contains this change:

https://github.com/jpdillingham/Soulseek.NET/commit/648ca4b1b71b8f4429d894d92362b83beb0fad57

This should help with transfers that fail but later succeed; I think part of the problem is that the remote client takes a bit to respond to the transfer request.  This increases the timeout time for that response from the default 5 seconds out to 15 (or more, depending on what the inactivity timeout is).

**Comment by mtoniott** [comment]
It now works like a charm. Thank you for the quick solution and also thank you for the good work, thanks to you we have finally a good headless soulseek client ! :)

**Comment by jpdillingham** [comment]
Glad to hear it, thanks!
