### ISSUE TITLE
Feature requests: Add ability to change profile info, auto ban for people not sharing files

### ISSUE THREAD

**Issue by plasticpippo** [slskd/slskd#330]
i was wondering if features could be added

- profile info
- auto ban for people not sharing files

thanks for the great project, really enjoying it

**Comment by jpdillingham** [comment]
Both are planned but not yet on the roadmap.

I don't think I will add support for auto-banning for leechers because that's a permanent fix for what might be a temporary (and unintentional) problem.  I'm working on user groups now, and leechers will be identified and placed in a special group.  Users can then set limits for leechers, including disallowing downloads entirely.

**Comment by jpdillingham** [comment]
Handling of leechers is done via the built-in `leechers` user group, as documented here: https://github.com/slskd/slskd/blob/master/docs/config.md#built-in-groups

The ability to set user info was added in #392, but users can't yet set a picture.  That's captured in #193.

I'll close this since it is partially complete/captured elsewhere.  Thanks for the suggestions!

**Comment by plasticpippo** [comment]
That's great JP! thank you so much

**Comment by neofright** [comment]
> including disallowing downloads entirely.

@jpdillingham Would you mind please explaining how downloads for a specific user can be disabled? I have a user added to the leechers group who was downloading my entire library. I have set the groups download speed to 1 kb/s but there may be a better way?

**Comment by jpdillingham** [comment]
Some controls around this have been planned in #531 (adding a blacklist) and #388 (adding quotas)

I can expedite the work to add a blacklist this evening.

**Comment by jpdillingham** [comment]
@neofright #741 will be merged shortly, and i'll create a release shortly after that.  Once you're updated you can blacklist users by adding the following to your groups config:

```yaml
   blacklisted:
     members:
       - <username to blacklist>
```

**Comment by neofright** [comment]
> @neofright #741 will be merged shortly, and i'll create a release shortly after that. Once you're updated you can blacklist users by adding the following to your groups config:
> 
> ```yaml
>    blacklisted:
>      members:
>        - <username to blacklist>
> ```

You're a hero. Thanks for all that you do

**Comment by awsms** [comment]
Mh.. can you add speed_limit in a group definition?
```
  user_defined:
    deny_group:
      upload:
        priority: 999
        queue_strategy: FirstInFirstOut
        slots: 1
        speed_limit: 1 
      members:
        - nuisance_user_name
```
In this example, speed_limit is ignored, only the global value of speed_limit is applied
