### ISSUE TITLE
Pass-through basic Authentication header when security is disabled, for compatibility with reverse proxies

### ISSUE THREAD

**Issue by Steve-Brule** [slskd/slskd#339]
Requests to /hub and /api fail with error 401, having a different Authorization header than expected. Other requests succeed. ![image](https://user-images.githubusercontent.com/83868338/151890435-3becd624-2baa-4058-9f13-2a4201fd3e6d.png)

I am trying to use nginx basic auth in lieu of slskd's built-in auth mechanism. Is there a way to make this setup work?

**Comment by jpdillingham** [comment]
I'm not familiar with nginx enough to comment on this use case, but you can [disable authentication](https://github.com/slskd/slskd/blob/master/docs/config.md#authentication) altogether and it might work.  You'd be relying on nginx to secure both the static content and back-end calls.

**Comment by jpdillingham** [comment]
Please let me know if you have further issues, and if you get it working if you could share your nginx config I can add it to the documentation for others.

**Comment by Steve-Brule** [comment]
Yes, I've already tried to do this with slskd's auth on and off. With auth off, the Authorization header on the failing requests is "Bearer n/a".

**Comment by jpdillingham** [comment]
With auth disabled the code bypasses authorization configuration on startup and hard-codes values, so there's pretty much no way that slskd code should be returning a 401 in this scenario.  Disabling auth does require an application restart; please double check that you've done that since last disabling auth.

The `Authorization: Bearer n/a` header is added in the UI code when auth is disabled, so there's nothing abnormal there.

Can you share your current nginx config?  I'll have to stand up a server and see if I can reproduce the problem.

**Comment by Steve-Brule** [comment]
I've disabled and enabled auth multiple times in testing, restarting each time. Connecting to slskd:5000 and slskd:5001 confirmed that auth settings were applied.

When I mentioned the Authorization: Bearer n/a header, I meant that it is supposed to be "Basic <base64 of username:password>" to pass nginx's basic auth. All other requests have such a header and thus pass the authentication.

`## Version 2021/05/18
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name slskd.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    auth_basic "Restricted";
    auth_basic_user_file /config/nginx/.basic_auth/slskd;

    #enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        #enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        #enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        #set $upstream_app slskd;
        #set $upstream_port 5000;
        #set $upstream_proto http;
        #proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_pass https://slskd:5001;

    }

    location /robots.txt {
        auth_basic off;
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }
}`

**Comment by jpdillingham** [comment]
Ah, ok.  I wasn't connecting the dots here.  The 401 is coming from nginx because the fetch/XHR requests aren't being sent with `Authorization: Basic ...`.

I'm trying to think of ways that I could support this and have a couple of ideas, but I'm curious what other app you've gotten this to work with so that I might have a look and see how they are doing it.

**Comment by Steve-Brule** [comment]
Here are a few of the apps I use with functionally identical nginx configs:

https://github.com/berkut-174/webtlo
https://github.com/Sonarr/Sonarr
https://github.com/librespeed/speedtest

**Comment by jpdillingham** [comment]
After some investigation it appears that this is an easy change.  When authentication is disabled, I need to ensure the UI isn't sending `Authorization: Bearer n/a` (it shouldn't be sending this in the first place, so that's a bug somewhere), and instead should invoke axios with `withCredentials: true`, which should pass-through the `Authorization: Basic ...` header.

**Comment by jpdillingham** [comment]
I decided to give it a shot in #344 which should be out to the canary in about 30 minutes.  @Steve-Brule if you could please try this and report back I'd be grateful!

**Comment by Steve-Brule** [comment]
Hmm, still seems to happen. I tried out edge and firefox. I'm using slskd in docker, version Version: 0.14.3.65534 (0.14.3.65534-fca1ab0).

**Comment by jpdillingham** [comment]
Thanks for giving it a shot, I'll have to set up a reproduction.

**Comment by jpdillingham** [comment]
I was able to set up a simple reproduction:

```
	server {
		listen 5432;

		auth_basic "Restricted";
		auth_basic_user_file /etc/nginx/.htpasswd;

		location / {
			proxy_pass http://localhost:5000;
		}
	}
```

The change I made previously did fix the calls to `/api/`, however the calls to negotiate the websocket for SignalR are failing with a 401, and then breaking all subsequent calls.

**Comment by jpdillingham** [comment]
@Steve-Brule this was fixed on my end, please try it with your config and re-open this if it is still broken.
