### ISSUE TITLE
'P' connections are not reused in certain situations

### ISSUE THREAD

**Issue by mathiascode** [slskd/slskd#340]
There seems to be a bug where a new 'P' connection is initiated for every transfer request in certain cases. It only seems to happen if I browse a user from slskd, and start a few downloads before the 'P' connection used for the share browse request is removed for inactivity.

Might be related to https://github.com/slskd/slskd/issues/318

**Comment by mathiascode** [comment]
The issue becomes worse when the user slskd connects to has a closed port and uses Nicotine+, since Nicotine+ rejects the indirect connection request when a previous 'P' connection already exists. Nicotine+ should probably not do this, but this could explain some of the transfer timeouts.

**Comment by jpdillingham** [comment]
This was _probably_ introduced here: https://github.com/slskd/slskd/pull/300/files#diff-b7816aa86798b1ccc8f7860e3aff30e37a54f60991ba18cc6741ecf87a1734b2R122

I was throwing things at the wall trying to figure out why some transfer requests would fail, then immediately succeed on retry, or when requesting 10 files the first few would fail but the rest succeed.  At the time I believed the problem might be due to a half-open connection that the other side was no longer listening to, but this change didn't fix the problem and because it was intermittent I have no idea if it improved anything.

Later on I figured out that the transfer response was coming back super late, even though the connection had actually succeeded, and I made this change: https://github.com/jpdillingham/Soulseek.NET/blob/master/src/SoulseekClient.cs#L3075-L3076

Previously I'd only wait 5 seconds for the remote client to respond to the transfer request, and this now waits up to 15 seconds or whatever the connection inactivity timeout is.  This seems to have solved the problem, but I haven't tested this alone.

#342 removes the cache invalidation which should stop this behavior.  A canary build should be out shortly if you'd like to give it a t ry.

**Comment by mathiascode** [comment]
Thanks, seems to be fixed now.

**Comment by jpdillingham** [comment]
Thanks for reporting this!

Closed by #342.
