### ISSUE TITLE
Ability to run a script on download completion

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#348]
I currently use [betanin](https://github.com/sentriz/betanin) with qbittorrent to automatically send downloads to beets, streamlining the import into my library, it would be nice to have this functionality.

**Comment by jpdillingham** [comment]
Thanks for the suggestion! I think this is fairly easily doable, I just need to think of the interface.

Taking a look at betanin specifically, it looks like it wants to process an entire directory at the same time, which would be difficult to pull off, because Soulseek doesn't have a concept of albums or directories, just single files.  This is an issue that is holding back Lidarr integration as well.

I'll have to think of the best way to introduce functionality that groups files as an "album", perhaps a new button on the UI like "Download as Album" or something.

**Comment by jpdillingham** [comment]
To elaborate on the sticking point, acting on the completion of a single download is very straightforward; that's how the FTP integration works today.  Acting on the completion of a directory/album is more difficult because of a loose association between individual file downloads.

I think I probably need to introduce a way to download an entire directory; this would give me the ability to act when all of the files within it complete.

Unfortunately a feature like this will have a large degree of ambiguity due to the fact that some users don't arrange their shared directories as full albums.  Many do, but the outliers will cause this functionality to break.

I think over time this can be improved, especially when I (finally) implement the feature(s) that allow searching by MusicBrainz/Discogs IDs, and can therefore ensure that directories contain a full album before enqueueing them.

**Comment by tandy-1000** [comment]
That makes sense, I think "Download directory" probably makes more sense for most use cases until we have the musicbrainz integration, but yeah that makes sense about some directories being a mess..

**Comment by boyska** [comment]
Isn't it enough to have this logic:

 - WHEN a file has been downloaded
 - IF there is no other file being downloaded in the same directory
 - THEN run the script

?

While I agree that different users use directories differently, I see no problem in allowing a script being invoked when a directory has been completed. Users who prefer to download everything in the same directory will probably not find this script very useful, but that's quite obvious. The only thing that matters is set a clear expectation of the behavior, and clarify that this has no notion of _Album_, only _directory_.

jm2c

**Comment by jpdillingham** [comment]
Released in [0.22.0](https://github.com/slskd/slskd/releases/tag/0.22.0)

@boyska I forgot to thank you for the suggestion; the implementation is just as you described.

**Comment by boyska** [comment]
> Released in [0.22.0](https://github.com/slskd/slskd/releases/tag/0.22.0)
> 
> @boyska I forgot to thank you for the suggestion; the implementation is just as you described.

you welcome! I was enthusiastically reading the new release notes :) and I was wondering: how safe is this interpolation of JSON in the provided example? I can totally see how

```yaml
run: /home/foo/bin/myscript $DATA
```
can work very well: I just need to read stdin and consume it. If I were to use Python, that would be `json.load(sys.stdin)`, nobrainer.
But invoking the shell and just interpolating (without any kind of shell-quoting, if I understand correctly) seems to be exposed to a whole class of attacks (we can debate whether `slsksd` or the user is responsible for those attacks of course).
Wouldn't it be just simpler to always provide `$DATA` (and *only* that) on StandardInput? And then the user will write their own wrappers to do what they want.

**Comment by jpdillingham** [comment]
> Wouldn't it be just simpler to always provide $DATA (and only that) on StandardInput?

you can set it up that way if that's what you want; it is designed to be very non-committal about how it works (except for the data being serialized as json, of course)

under the hood the code takes the configured `run` string and splits it by spaces, taking the first word as an executable and the rest as arguments.  it then uses `Process.Start()` to invoke the executable and passes the rest of the string -- whatever it is, including just `$DATA` if you want -- to stdin.

as i'm writing this out i am questioning whether this will actually work the way i imagined across all platforms; i'll have to do some additional testing and potentially expand `run` to include both `arguments` and `stdin` so the behavior is more clear and controllable

**Comment by boyska** [comment]
> you can set it up that way if that's what you want; it is designed to be very non-committal about how it works (except for the data being serialized as json, of course)

well, sure. And of course the user can shoot themselves in the foot.

But it's my opinion that at least the documented example should not be buggy, and I'm afraid it might be buggy in a way which exposes the user to security hacks by random people on the network (I'm not keen on `cmd.exe`, so I might be wrong, but simlar code can definitely be exploited on `sh`). Do you agree this is the case?

**Comment by jpdillingham** [comment]
@boyska active discussion has moved to #1278, would appreciate it if you could bring your thoughts.
