### ISSUE TITLE
Incoming searches

### ISSUE THREAD

**Issue by Daniel15** [slskd/slskd#391]
Is there a way to see incoming searches, like the Qt client has?

**Comment by Daniel15** [comment]
Just realised this is already in the logs

**Comment by jpdillingham** [comment]
It's logged when responding to a request, but requests for which there were no results aren't logged.

I've been thinking for a while how I could add support for this because I think it would be interesting to see what people are searching for, however the volume of incoming searches is very high and any attempt to log them or save them to a database would negatively impact overall performance.

I will eventually add better logging and persistence (at least keep counts) of delivered search results.

**Comment by Daniel15** [comment]
How does the Soulseek Qt client do it? Are they just entirely in RAM?

I wonder if you could use a ring buffer and store (for example) the last 10000 received searches.

**Comment by jpdillingham** [comment]
As far as I know most if not all diagnostics are in RAM only.

A buffer would be a good idea; the logs in the system section of the UI are done the same way, implemented through [ConcurrentFixedSizeQueue](https://github.com/slskd/slskd/blob/master/src/slskd/Common/ConcurrentFixedSizeQueue.cs)
