### ISSUE TITLE
Uploads/downloads pages slow to render and scroll when there's a lot of items

### ISSUE THREAD

**Issue by Daniel15** [slskd/slskd#393]
Maybe this page needs some sort of windowing technique so it only renders what's visible in the viewport (see the react-window library for example).

**Comment by jpdillingham** [comment]
Thanks for raising this.  This is an issue with transfers and the "treeview" that displays browse responses.

For transfers I plan to eventually create a collapsed view for each user that will display only directory names and summarized progress (completed/total files, total % completion).  This will help, and make completed transfers easier to clear, but it won't solve the problem completely.

Either windowing or bypassing the React DOM altogether for the browse treeview is likely the only answer.  I don't really care for the UX of this feature but I haven't been able to come up with an alternative that works on mobile.

**Comment by rakbladsvalsen** [comment]
I don't think this issue requires "hacky" solutions (i.e. the windowing/react DOM thingy). I haven't taken a look at slksd's code, but maybe pagination would be something easier to implement (and probably the most reasonable solution, since it won't be sending the whole file list on each update). Pagination is also friendly with mobile devices.

I came across this issue and it takes an eternity to load when there are a lot of uploads/downloads.
