### ISSUE TITLE
Reconfiguring shares causes some remote users to re-request files that still exist, but can't be resolved from the request (the mask changes)

### ISSUE THREAD

**Issue by Rafaeltheraven** [slskd/slskd#420]
I see a bunch of error messages with the following format in my logs:
```
Failed to resolve shared file "@@nlbqv/music/{name}/processed/Amy Winehouse - Back to Black/Amy Winehouse - 11 - Addicted.flac"; unable to resolve share from mask '"@@nlbqv"' and alias '"music"'
```
However, when I try to download these myself from another device, everything seems to work and there's no warnings in the logs, what does this mean?

**Comment by jpdillingham** [comment]
This will generally happen if you've recently reconfigured your shares and a remote client has a browse or search response that was sent from an old configuration.

Have you changed anything recently?  If not it may be a bug.

**Comment by Rafaeltheraven** [comment]
At the time of writing I had just setup slskd, so the config was changing a lot, but it is still occuring 3 days later, and I've not changed anything in the meantime.

**Comment by jpdillingham** [comment]
@Rafaeltheraven apologies for losing track of this.  Are you still having issues? 

If so, could you enable [debug mode](https://github.com/slskd/slskd/blob/master/docs/config.md#development-flags) and email a screenshot or text file of the startup logs to logs@slskd.org?  It will help me understand what the issue might be.

**Comment by Rafaeltheraven** [comment]
Seems to still be happening as of 0.16.3. Just updated and running with the debug flag, will send later

**Comment by jpdillingham** [comment]
Thanks for sending the logs and config over.  I've had a look, and I think what is happening is that there are a couple of users that are continually retrying downloads that are no longer tracked.

All of the failures resolving files (at least, all of the failures in the logs and the one in your post here) are referencing a mask `@@nlbqv`, while your current mask is `@@mdqqe`.  The files are actually there, but the mask is wrong so slskd can't find them.

Masks are just hashed representations of the paths to your shares; for instance, if you share `/var/user/music` it might show up to remote users as `@abcde/music`.  When you move your music to say, `~/user/Music`, it might show up as `@edcba/music`.

In this case, users either browsed your shares or got search results from you when your music was stored in one place, and are asking for _those_ files, but they have moved.

We have a couple of options:

* Leave things as they are.  Remote users should be getting 'file not shared' when this happens and should eventually take the hint and stop asking
* Update the logic to resolve filenames from hashes to search for the file elsewhere when it can't find the file.  This would fix the problem, but it also raises the risk that someone gets a file they were not intending to get 
* Give users the ability to alias masks.  In this case, aliasing `@@nlbqv` to `@mdqqe` would solve the problem and allow these users to complete their downloads

I'm leaning towards the latter solution, but I feel like this problem is so obscure nobody would know to use it.

@mathiascode interested to hear how you are handling this.  If an alias is updated, does Nicotine+ 'remember' what it used to be? Or do requests using the old alias just fail?

**Comment by mathiascode** [comment]
Requests fail if the path is no longer the same. Nicotine+ has virtual names for shared folders (say you share /home/user/Music, give it a virtual name "Collection", the virtual path will be Collection/file.mp3) so the user can just move the folder, reshare it, and use the same virtual name as before.

**Comment by jpdillingham** [comment]
@Rafaeltheraven unfortunately whatever is causing these clients to continually re-request these files is not going to be solved by the change I just made, but the change to how share aliasing works should prevent remote clients from becoming confused by this in the future.

**Comment by Rafaeltheraven** [comment]
Oh well it's something. It wasn't really an issue for me, just something I noticed.
