### ISSUE TITLE
Official slskd community in Discord/Telegram/whatever

### ISSUE THREAD

**Issue by droserasprout** [slskd/slskd#447]
It would be nice to have a single place for conversations not valuable enough to store in GitHub forever. Personally important for me, since I'm gonna spend lots of time on this project, and thus need to sync plans with you often, @jpdillingham.

**Comment by jpdillingham** [comment]
I'd love this, but I'm not a big Discord user and from what I've seen moderating a server takes a lot of effort.  Any volunteers?

I guess maybe I could create one and see how it goes with a default setup.

**Comment by droserasprout** [comment]
A single chat anywhere will be more than enough; I don't think we'll have to deal with server moderation at this stage 😌

**Comment by tandy-1000** [comment]
An unencrypted Matrix room would be great!
It could be bridged to Discord, Telegram, etc. further down the line, there are some useful bots for moderating bridged chats too..
(Unencrypted because encryption probably won't be necessary(?) and its a lot faster / more flexible)

**Comment by edgar-vincent** [comment]
I agree with @tandy-1000 and just created a room on Matrix for you to try. It can be reached at #slskd:matrix.org (and via https://matrix.to/#/#slskd:matrix.org if you want to use Element as a web client).

**Comment by jpdillingham** [comment]
Sorry for dragging feet on this.  I think Discord is the most approachable option.  I like the idea of Matrix but last I checked it was a bit cumbersome to use, and it looks like we can link the two.

I've created a Discord server; the invite link is:

![image](https://user-images.githubusercontent.com/17145758/166926929-b9e62a9c-1a3c-431f-b390-9d577afb3060.png)

Please forgive the screenshot instead of a clickable link; I don't want to give spambots an easy way to find their way in.

**Comment by edgar-vincent** [comment]
Should this be closed? The Discord and Matrix channels (which are now bridged) should probably be mentioned in the README.

**Comment by jpdillingham** [comment]
I added badges to the readme for both Discord and Matrix, along with redirects to hopefully help keep some bots away:

https://slskd.org/discord
https://slskd.org/matrix

I'll close this issue.  @droserasprout not sure if you saw this but I'd love to connect!
