### ISSUE TITLE
Send upload speed and slots in search and user info responses

### ISSUE THREAD

**Issue by mathiascode** [slskd/slskd#489]
Currently slskd sends hardcoded default values for upload speed and slots.

**Comment by jpdillingham** [comment]
Thanks for the reminder!  I scroll past this in my editor once in a while and make a mental note to create an issue but haven't been able to remember.

**Comment by jpdillingham** [comment]
@mathiascode how are you handling the computation of queue depth and/or place in line requests?

I built a ton of non-determinism into my queue so the best I can do is an approximation based on the known data a the time (I guess that's the best any client could do, really) but for place in line requests any number I give would almost certainly be wrong.  I'm guessing that's why it doesn't work in newer versions of Qt.

**Comment by mathiascode** [comment]
> @mathiascode how are you handling the computation of queue depth and/or place in line requests?

https://github.com/nicotine-plus/nicotine-plus/blob/f6ed668cc4c82628a0361f537f0d77a711c6e38f/pynicotine/transfers.py#L1453

FIFO should be accurate. Round robin assumes all other queued users have as many uploads as the requesting user, so it's slightly inaccurate. I now realized I should add support for privileged users in the round robin part of the code.

I could probably make it more accurate with various tricks, but I don't want the code to become a larger performance bottleneck, since queue positions are requested in bulk.

> I'm guessing that's why it doesn't work in newer versions of Qt.

I think it would be more likely that the uploader has free slots, but one user has requested several albums worth of files, resulting in a large queue count. I haven't looked into it though.

**Comment by mathiascode** [comment]
Queue count in search results: https://github.com/nicotine-plus/nicotine-plus/blob/f6ed668cc4c82628a0361f537f0d77a711c6e38f/pynicotine/transfers.py#L1764

**Comment by jpdillingham** [comment]
I forgot to circle back on this after the PR was merged!

This ended up being easier than I expected, primarily because I made no attempt to solve for higher-precedent groups that might "steal" slots from other groups.  

In a perfect world, if a privileged user enqueued 20 files every non-privileged user should see their files move 20 spots down in the queue.  In reality their files stay in the same spot, they just have to wait longer.  This might be me rationalizing, but I think this is a better UX from the perspective of the remote user.
