### ISSUE TITLE
More persistent /app-data?

### ISSUE THREAD

**Issue by kromsam** [slskd/slskd#523]
There are some instances that make me wonder if slskd couldn't save more data in its `/app` persistent volume. Data that now gets lost on a restart. For instance:

- running downloads, and the list of completed/failed downloads
- running uploads, and the list of completed/failed uploads
- rescanning the shares

is there a reason we lose this data on a restart? Otherwise, it would be especially great if downloads would just continue on a restart of slskd. Now a restart of slskd means that one has to re-search and restart certain downloads.

I do have to say, I love slskd and the work you keep putting in to make it better and better. This project could really turn out to be one of the major soulseek clients.

**Comment by mgoldspink-salesforce** [comment]
I was going to file the same issue. It'd be great to have status of downloads kept across reloads.

**Comment by jpdillingham** [comment]
Re-requesting downloads is _sort of_ blocked by #406 (resumable downloads) since anything in progress when the app is restarted would be stuck in a non deterministic state.  To do this right I'll also need to monitor each user with enqueued downloads and re-request files both after a restart, and if that user goes offline and comes back online.  This is unfortunately a shortcoming that exists today; if files are enqueued they may stay enqueued indefinitely.

There's not much of a reason that completed uploads and downloads aren't persisted across reboots, other than it was all in memory when it was originally created for the Soulseek.NET example app and it just didn't seem like a priority.

Running uploads and anything queued should be re-requested by the remote user, so there's not much to be done to make that work.

I considered saving the share cache to disk and reloading it on start instead of scanning from scratch, but internally it uses a dictionary along with an in-memory SQLite table (for full-text searching) and I'm not sure the benefit would be worth the added complexity.

**Comment by kromsam** [comment]
Thanks for your reply. I think some things might are indeed complex. And not everything is just as important

> There's not much of a reason that completed uploads and downloads aren't persisted across reboots, other than it was all in memory when it was originally created for the Soulseek.NET example app and it just didn't seem like a priority.

Although I think that this would be a nice feature. Sometimes when I reopen Soulseek and all my downloads are gone, I kinda miss track of what already is downloaded, and which downloads I short give another try. With Soulseek you sometimes need to try a specific download a couple of times before it runs and it would be nice to keep those downloads in tact as a sort of 'wish list'.

**Comment by jpdillingham** [comment]
I hear you; I've been struggling to keep track of things since I added the ability to add a bunch of searches one after the other.  I think a lot of this will be improved when [Guided Search](https://github.com/slskd/slskd/milestone/3) is implemented, but I'm leaning towards taking some extra time in the current phase to build this out.

Just to set expectations, here's a high level list of what needs to be done:

* [#710 in Soulseek.NET](https://github.com/jpdillingham/Soulseek.NET/issues/710)
* Add a 'preferences' construct (or similar) to options where I can stuff one-off options
* Add a one-off option for file resume behavior (options: overwrite, append.  default to overwrite)
* Update download logic to check for existing files on disk, grab the size, and use it when making the download request to resume
* Persist downloads to a new database file (probably downloads.db) and load them on start
* Add logic to re-enqueue any incomplete downloads after the client connects
* Add logic to re-enqueue any incomplete downloads when the remote user comes back online
* Add logic to pause (maybe?) downloads when the remote user goes offline

It's kind of a lot 😅 

Some of this becomes inconsequential when Lidarr enters the picture, but not everyone will be using Lidarr so it'll need to be done regardless.

I'll take some more time to create some issues and a milestone for this.

**Comment by jpdillingham** [comment]
Starting with release [0.16.9](https://github.com/slskd/slskd/releases/tag/0.16.9) transfers (including uploads and downloads) are now stored in a SQLite database in `/app/data`.  There were some bumps along the way, and as of release [0.16.17](https://github.com/slskd/slskd/releases/tag/0.16.17) I think it is safe to consider this issue closed.

A refactor of share scanning logic has now become its own [milestone](https://github.com/slskd/slskd/milestone/5).
