### ISSUE TITLE
<x> is not enqueued for <user>

### ISSUE THREAD

**Issue by benzo8** [slskd/slskd#583]
slskd 0.16.8.0 (0.16.8.0-e4644eb), docker-image: slskd/slskd:latest
Ubuntu: 20.04.4 LTS

I'm seeing a lot of errors thus: 

```
17:18:38	INF	["UPLOAD REQUESTED"] "<user>" requested "<file>"]
17:18:38	WRN	Failed to resolve place in queue for file <file> from <user>: File <file> is not enqueued for user <user>
17:18:38	WRN	Failed to estimate place in queue for "<file>" requested by "<file>"
```

Sometimes this seem to mean the file never makes it to queue and sometimes it's a case of the file erroring out.

**Comment by jpdillingham** [comment]
Thanks for reporting this, I can confirm that it's a bug.  It seems like it is easy to reproduce, and it's something that was introduced recently.

Checking my own logs, it might be that incoming filenames use a mix of forward and back slashes in paths.  This has been a contentious thing in the past with different clients having different behavior so that's where I'll look first.

**Comment by jpdillingham** [comment]
What's happening is that some clients send a `PlaceInQueueRequest` immediately after the request to download a file.  Because the process to enqueue a file runs asynchronously, the `PlaceInQueueRequest` was being handled, in most cases, before the upload was fully enqueued.

The code in slskd was incorrectly throwing an exception and Soulseek.NET was logging the warning; by designed the correct behavior is to return `null` instead of throwing, in which case no warning is logged.
