### ISSUE TITLE
Search filter 'islossy' retains .flac results that don't specify a bit depth

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#624]
I'm pretty sure this is because some clients don't send enough properties (e.g. bit depth) to tell whether a file is lossless or not, in which case I can't do anything to improve this.

This is more of an investigative issue; double check that filtering is indeed 'as good as it gets'.

**Comment by mathiascode** [comment]
Nicotine+ is probably responsible for these results, since we send bitrate for all audio files, but you will get false positives from SoulseekQt for files with an .m4a extension, which can be either lossy or lossless.

I think the safest solution is to add a fallback that checks if the bitrate is 320 kbps or lower.

**Comment by mathiascode** [comment]
I've made a change in Nicotine+ to send the sample rate and bit depth of lossless files (properly detects if a file with a .m4a extension is lossless): https://github.com/nicotine-plus/nicotine-plus/commit/3cdcc049349d99b2f6e4dd2dd318260fcbe97349

**Comment by mattgoldspink** [comment]
Yeah I've tested this locally and it seems like the filtering on slskd side is working correctly when the right data is sent.

**Comment by jpdillingham** [comment]
Similar to #625, the root cause is that filters include files that can't be excluded, as opposed to including files that explicitly match.  I don't think this can be improved because the absence of a bit depth is the only way to really tell.

Thanks for the feedback!
