### ISSUE TITLE
Slow scanning?

### ISSUE THREAD

**Issue by MitraMai** [slskd/slskd#698]
Hello!
I've set up slskd on my raspberry pi4, the shares are on an external HDD which is mounted through NFS and (and systemd, if that might have any importance). I started the scanning yesterday, and I've turned on Debug-mode. The share is about 296 gb big, and contains 2289 directories. The library layout is: 
Artist > Album(s)
So most of the directories are sub-directories.
Now, 17 hrs later slskd has only scanned 810 directories. And I can't reach the website. The info I get from **systemctl status slskd.service** (which confirms that slskd is up and running) and the logs.
Is it normal that a scan takes this long? I haven't seen anything unusual in the logs (from what I can tell at least)
I rather not attach the logs, but can send them on request.

Edit: I'm running version 0.16.24
Edit 2: I have the default value of workers, 16. And I just read that the app might become unresponsive. So that explains why I can't reach it through the web

Regards
/M

**Comment by jpdillingham** [comment]
I haven't tried scanning over NFS, but I imagine this is why it is slow. Are you using Wi-Fi? or Ethernet?

You might try changing the number of cache workers (described [here](https://github.com/slskd/slskd/blob/master/docs/config.md#cache)) to see if that helps.  In testing I found that additional workers increased performance, but I'm not sure if that would be true over NFS as well.

**Comment by MitraMai** [comment]
The library is mounted through NFS over Ethernet. So the ideal would be to have the the HDD mounted directly on the RPI4 then... Now the NFS-server is another RPI4.
I'll let this run until the library is scanned, and then I might change the config and see if I get a better result.
Thanks for the quick reply

**Comment by jpdillingham** [comment]
To give you an idea of what's going on during a scan, it first enumerates all directories (including subdirectories) in the root of the share, then starts iterating over each, first enumerating all of the files (not including subdirectories) and then inspecting each file to check the length, bitrate, etc.

The enumeration stages are fairly quick because there are OS-level mechanisms for doing this (same if you `du /`).  The part that's really slow is the checking of the files.

Depending on how things are implemented under the hood (below my code, that is) the entirety of each file might be read into memory to extract the metadata.  Even if it isn't each file has to be opened, then a seek done to find the metadata etc.  The bottleneck(s) in this case will be the network as well as disk I/O on the system that's connected to the hard drive.

Worth mentioning is that I'm working on a client/server type of architecture that will help people host their files on a system other than the one running slskd.  You can read about it in #688, or if you're feeling brave you could check out the canary release from #697 this morning which is a rough implementation.  Let me know if you're interested and I can walk you through the setup.

**Comment by MitraMai** [comment]
Thanks for the detailed explanation. Yes, I can understand that it takes time to go through all these steps if the share is mounted through NFS. 
Regarding trying out the Canary release, thanks, but no thanks. I don't feel brave enough and for the moment I spend to much in front of the screen trying out new setups and optimizing the ones I have so I have to pass :D

**Comment by jpdillingham** [comment]
Work is wrapping up on the new 'Relay' functionality (the client/server architecture I mentioned), so I'll close this issue.
