### ISSUE TITLE
Error updating on to new image

### ISSUE THREAD

**Issue by tge101** [slskd/slskd#73]
Pulled latest image and am getting the following error

App directory slskd does not exist, and could not be created: The file '/slskd/slskd' already exists.
App directory slskd is not writeable: The file '/slskd/slskd' already exists.

**Comment by jpdillingham** [comment]
Thanks for reporting this, I'll try it on my end in a few minutes.  Are you
specifying anything for the app directory setting?

**Comment by tge101** [comment]
Nope.  I tried reverting back to the previous image and I'm getting the same error.  Below is the stack I use in Portainer

version: '2.1'
services:
  web:
    environment:
      - PUID=1000
      - PGID=100
      - "SLSKD_SLSK_USERNAME=username"
      - "SLSKD_SLSK_PASSWORD=password"
      - "SLSKD_USERNAME=username"
      - "SLSKD_PASSWORD=password!"
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - /srv/dev-disk-by-label-Media/Music/downloads:/var/slskd/downloads
      - /srv/dev-disk-by-label-Media/Music:/var/slskd/shared
    image: slskd/slskd:latest
    restart: always

**Comment by jpdillingham** [comment]
This appears to be a misunderstanding on my part (or I just neglected to test) of how `Environment.SpecialFolder.LocalApplicationData` works in Docker.  This appears to be returning an empty string, which is combined with `slskd` as the application name, and then this is being assumed to be a relative path to the working directory within the container (resulting in `slskd/slskd`).

**Comment by jpdillingham** [comment]
Reopening this until I can confirm that the resulting image works.  I ran the 0.10.0 container interactively and was able to get it to start by exporting `SLSKD_APP_DIR`, so a change to the Dockerfile to set this during the build should result in the same outcome.

This should fix the problem on _this specific Docker image_ but any others will fail due to the odd behavior with `LocalApplicationData`.  I suspect it comes back blank either because the directory doesn't exist, or because the path doesn't resolve for root for some reason.

**Comment by jpdillingham** [comment]
The `latest` tag with 0.10.1 should be fixed, please give it a try and let me know if it solves your problem.

**Comment by tge101** [comment]
Yup.  Up and running with the latest image.  Thank you for the quick fix.
