### ISSUE TITLE
Unable to clear upload page

### ISSUE THREAD

**Issue by mortelil** [slskd/slskd#962]
After letting slskd run on my server for a few weeks without any supervision, and sharing a lot of files on a gigabit connection. I am unable to do anything on the upload page. Firefox slows down a lot when visiting the page, and suggest I stop scripts. I have been able to click the "remove all succeeded" button, and the icon is spinning occasionally, but it's been over an hour and it still haven't been able to clear the completed files.

I'm both looking for a solution to clear my files from the upload page, and for slskd to handle this in a better. Maybe only showing 100 uploaded files and having a "show more" button on the bottom of the page.

**Comment by jpdillingham** [comment]
Unfortunately this is a known issue that I haven't had time to fix due to lack of a better design for this page.  I added a workaround that will allow you to clear the data, which you can access by going into 'System', selecting the 'Data' tab and then clicking the button:

![image](https://github.com/slskd/slskd/assets/17145758/635cfec5-3756-4191-9e92-83e616eeb0f0)

I think the easiest path forward would be for me to add an option to remove completed uploads automatically, that way only active uploads would show up.  I would then need to add a way for users to see their history, and I need some time to think about that.

**Comment by mortelil** [comment]
Thanks for your quick reply! I didn't think of checking the data tab, all good now. I've limited both my upload slots and my upload speed, cause the amount of files I was uploading was a bit too much. Thanks a lot for the great software!
