### ISSUE TITLE
When adding in new retention options YAML goes invalid

### ISSUE THREAD

**Issue by mon5termatt** [slskd/slskd#994]
![chrome_mZGDkxNonF](https://github.com/slskd/slskd/assets/43628254/ad7a4dca-b36b-43d9-b885-ec3b4f493ce8)
When adding in retention options i can uncomment the retention line and get `Did not find expected <document end>.`

**Comment by jpdillingham** [comment]
I'm guessing you got it sorted out since you've closed this.  What was the issue?  I tried to reproduce it this morning and couldn't find the right combination of things to uncomment.  I also don't recall getting that message before.

A little insight into how this works; your changes are sent to the backend in real time and thrown against the YAML parser.  If any of those requests fail the error message is displayed.

I'm thinking maybe I should stop doing that in real time and instead add a "Validate" button; it's annoying to have it pop up while you're typing.  What do you think?
